language: objective-c
osx_image: xcode8
xcode_project: BehaviourBasedTransitions.xcodeproj
xcode_scheme: BehaviourBasedTransitions

script:
  xcodebuild build
  -project BehaviourBasedTransitions.xcodeproj
  -scheme BehaviourBasedTransitions
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6'
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGNING_REQUIRED=NO
