language: objective-c
osx_image: xcode8.0
xcode_project: BehaviourBasedTransitions.xcodeproj
xcode_scheme: BehaviourBasedTransitions

script:
  xcodebuild
  -project BehaviourBasedTransitions.xcodeproj
  -scheme BehaviourBasedTransitionsTests
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6'
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGNING_REQUIRED=NO
