language: objective-c
osx_image: xcode7.3.1
xcode_project: BehaviourBasedTransitions.xcodeproj
xcode_scheme: BehaviourBasedTransitions

script:
  xctool
  -project BehaviourBasedTransitions.xcodeproj
  -scheme BehaviourBasedTransitions
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6'
  build
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO
