language: objective-c
osx_image: xcode8.2
xcode_project: BehaviourBasedTransitions.xcodeproj
xcode_scheme: BehaviourBasedTransitions

script:
  xcodebuild
  -project BehaviourBasedTransitions.xcodeproj
  -scheme BehaviourBasedTransitionsTests
  -sdk iphonesimulator
  -destination 'id=BE8E0914-5B5F-45C2-8C99-879894AF72B0'
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGNING_REQUIRED=NO
